# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOPT-week1-assignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOPT-week1-assignment
  pod 'Alamofire'
end
